---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  namespace: edu-goofy-allen
data:
  SECRET_KEY: "your_secret_key_here"
  DEBUG: "False"
  ALLOWED_HOSTS: "127.0.0.1,localhost,edu-goofy-allen.sirius-k8s.dvmn.org"
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-goofy-allen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: wombatoff/django-app:latest
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: ALLOWED_HOSTS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: port

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: secret_key
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: bucket_name
            - name: AWS_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: endpoint_url
...

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-goofy-allen
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30351
...
